version: '3.7'

services:
  api:
    container_name: api
    image: soraiafreitas/ems
    ports:
      - 8000:80
  client:
    container_name: client
    build:
      context: .
      dockerfile: ./.docker/nodejs/Dockerfile
      target: develop
    ports:
      - 4200:4200
    volumes:
      - ./source/client:/usr/src/app/angular
